//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participante
    {
        public int Id { get; set; }
        public int IdChurras { get; set; }
        public string Nome { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<bool> Pago { get; set; }
        public Nullable<bool> ComBebida { get; set; }
    
        public virtual Churra Churra { get; set; }
    }
}
